### PR TITLE
Remove deprecated header get_env.h

### PR DESCRIPTION
**Pull request by emersonknapp**
Per deprecation notice @christophebedard

### CODE REVIEW

**Comment by clalancette** [comment]
Same comment as: https://github.com/ros2/rclcpp/pull/2139#issuecomment-1481756802

**Review by fujitatomoya — APPROVED** [review]

**Review by wjwwood — APPROVED** [review]

**Review by clalancette — APPROVED** [review]
Looks good with green CI and assuming https://github.com/ros2/ros2_documentation/pull/3403 gets merged at the same time.

**Comment by clalancette** [comment]
This one probably needs a rebase.

**Comment by clalancette** [comment]
CI after rebase:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18312/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12834/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18978/)

**Pull request merged**
