### PR TITLE
[Eloquent] check and link against libatomic (#172) (#178)

### PR DESCRIPTION
**Pull request by sloretz**
Cherry-pick #178 to `eloquent`.

### CODE REVIEW

**Comment by sloretz** [comment]
@nkueng FYI. This backports #178 to `eloquent`. I made this by checking out the `eloquent` branch, and cherry-picking the changes from #178 onto it.

```
git checkout eloquent
git checkout -b my_eloquent_backport_of_178
git cherry-pick -s af3e145
```

In the future, you can use those steps to try new changes on an old branch. When this PR is merged, you'll just need to use the `eloquent` branch.

**Comment by sloretz** [comment]
PR job looks good. Since this is just a backport I think full CI can be skipped.

**Comment by nkueng** [comment]
@sloretz Thank you very much for the explanation! But why wasn't it fixed on the `eloquent` branch in the first place? Also, one more thing if I may ask since I can't find any suitable documentation for this: I am following the [official tutorial](https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Development-Setup/) for building ros2 from source, but can't figure out how to only download/build the bare-bone packages of ros2 (i.e., what `ros-eloquent-ros-base` gets you if you're installing from a Debian package). I see I could add an `AMENT_IGNORE` flag in every package I don't want to build, but there must be a way to only download the ones I need in the first place?
Once again, I am very grateful for every hint I get!

**Comment by sloretz** [comment]
@nkueng happy to help!

Would you mind asking follow up questions on https://answers.ros.org/ and tagging them with `ros2`? Comments on merged pull requests have a high risk of not being responded to. Merged pull requests and closed issues are not very visible, and not nearly as many people have notifications for them as for questions on ROS Answers. You mind fine the [support guidelines](http://wiki.ros.org/Support) useful.

**Pull request merged**
