### PR TITLE
Control shared/static linking via BUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by esteve**
Not ready for review, just submitted this so that it's added to ros2/ros2#306

Connects to ros2/ros2#306

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Closing in favor of rebased version in #94.

**Comment by esteve** [comment]
@dirk-thomas thanks, though it seems the branch didn't have any conflicts that needed a rebase anyway.

**Comment by dirk-thomas** [comment]
> though it seems the branch didn't have any conflicts that needed a rebase anyway.

Since it was created a while ago if anyone tried to use it it wasn't "in sync" with the master branches of the other repos. Therefore it has been rebased / fast forwarded to get a current version of the repository.

**Comment by esteve** [comment]
> Since it was created a while ago if anyone tried to use it it wasn't "in sync" with the master branches of the other repos. Therefore it has been rebased / fast forwarded to get a current version of the repository.

No worries, I thought the CI rebases branches/merges before running a job, but I might be mistaken. Anyway, thanks for taking care of the PR.

**Comment by mikaelarguedas** [comment]
> I thought the CI rebases branches/merges before running a job

Unfortunately CI is able to do this only on branches hosted on our repos (cloning the ros2.repos file and merging with the default branch). It's not able to to this on forks yet so we need to rebase manually

**Comment by esteve** [comment]
> Unfortunately CI is able to do this only on branches hosted on our repos (cloning the ros2.repos file and merging with the default branch). It's not able to to this on forks yet so we need to rebase manually

Ah yeah, that's true, I forgot about that! Thanks for the explanation.

**Pull request closed without merging**
