### PR TITLE
Remove references of __xstat

### PR DESCRIPTION
**Pull request by paeunt**
As mentioned in [issue 329](https://github.com/ros2/rcutils/issues/329).
 I've removed some refs of __xstat to fix building errors in Arch Linux. Also tested passed on Ubuntu 18.04 and Ubuntu 20.04. 
__xstat was removed in glibc 2.33, so do not use it anymore.

### CODE REVIEW

**Comment by clalancette** [comment]
It looks like the tests failed in CI; that's likely because mimick needs this function to mock everything properly.  @hidmic could you take a look and maybe provide some context here?

**Comment by paeunt** [comment]
Maybe I should add a version constraint in CMakeLists.txt.

**Comment by clalancette** [comment]
The idea here looks OK to me.  I'm going to run a full CI on it on all platforms to see what happens.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13805/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8673/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11514/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13890/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13891/)

**Comment by clalancette** [comment]
All of the unstable tests on Windows are also unstable on the nightlies, so there don't seem to be any regressions here.

I'd still like to get @hidmic's opinion before merging, so I'll hold off on merging this one for now.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
I'm going to go ahead and merge this one.  @hidmic feel free to leave comments afterwards if you have any concerns.

**Pull request merged**
