### PR TITLE
time sanity checks

### LINKED ISSUE #88: sanity check for rcutils_steady_time_now
`rcutils_steady_time_now` currently trusts the OS specific implementations to provide truly monotonic time values. Issue #86 and [Internet](https://stackoverflow.com/questions/3657289/linux-clock-gettimeclock-monotonic-strange-non-monotonic-behavior) show the monotonicity claim should be verified.

### PR DESCRIPTION
**Pull request by serge-nikulin**
- monotonicity check
- overflow checks

closes #88

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks for the pr, I will need to make some changes to allow us to accept it, but I'm working on a pr for that now. I just wanted to make sure others weren't also doing the same thing.

**Comment by serge-nikulin** [comment]
@wjwwood, do you have ETA for this one? I would like to fork *after* this one. Thanks!
CC: @dejanpan

**Comment by wjwwood** [comment]
@serge-nikulin I've been working on this, but there are a few things I'm trying to address in this pr before I'd consider it for merge:

- provide a way to force memory allocation in the initialization of the thread-local storage so it is avoided during runtime
  - allocation can occur on first access of thread-local storage in new threads, even when using the new `thread_local` keyword, but especially when you implement using pthreads
- provide a pthread based implementation, since we've had users which build on iOS which doesn't implement `thread_local` or `__thread`
- provide a way for users to disable the checks

So I don't have an eta yet, but I'm working on it.

**Comment by serge-nikulin** [comment]
@wjwwood, how about using shared, non-TLS `last sample` and serializing access to it with interlocked update, critical section, mutiex, etc?

**Comment by wjwwood** [comment]
@serge-nikulin can do that too, but then this function is not lock free anymore. And it could potentially be a high contention lock. I'll think about it though.

**Comment by wjwwood** [comment]
I'm going to close this. I don't think it's unreasonable to rely on the OS to give us monotonic time. If someone is concerned about this they may cherry-pick this patch or a similar one into their local version for debugging.

I know the idea was to have this catch this nonobvious issue early, but the cost of having either a thread-local variable (which may allocate on the first access in each new thread), a lock which may be highly contentious, or something else doesn't seem worth it.

If someone wants to continue pushing on this issue let me know and I'll reopen it.

**Pull request closed without merging**
