### PR TITLE
Specify working directory for filesystem test

### PR DESCRIPTION
**Pull request by rotu**
Prevent anticipated breakage from https://github.com/ament/ament_cmake/pull/206
Signed-off-by: Dan Rose <dan@digilabs.io>

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Why is this necessary if the new default is `CMAKE_CURRENT_SOURCE_DIR` anyway?

**Comment by rotu** [comment]
It's not. The new default is `CMAKE_CURRENT_BINARY_DIR`

**Comment by dirk-thomas** [comment]
> It's not. The new default is `CMAKE_CURRENT_BINARY_DIR`

:open_mouth: See https://github.com/ament/ament_cmake/pull/206#issuecomment-545566943

**Comment by dirk-thomas** [comment]
Thanks.

**Pull request merged**
