### PR TITLE
avoid unnecessary copy for rcutils_char_array_vsprintf.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rcutils/issues/409

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@clalancette minor improvement, can you review on this?

**Comment by fujitatomoya** [comment]
CC: @iuhilnehc-ynos

**Review by iuhilnehc-ynos — COMMENTED** [review]
I am afraid we should update `_rcutils_char_array_vsprintf` by removing `va_copy` inside.
Please consider this case,
https://github.com/ros2/rcutils/blob/017b05c9f854fd7f49466e1c5331558aae92e44b/test/test_char_array.cpp#L42-L52
Do you think `_rcutils_char_array_vsprintf` still needs the `va_copy`?

I'd like to use `va_copy` before `rcutils_char_array_vsprintf` if needed. What do you think?

**Comment by iuhilnehc-ynos** [comment]
I think I know why `_rcutils_char_array_vsprintf` needs to call `va_copy`, because `_rcutils_char_array_vsprintf` might be called twice in `rcutils_char_array_vsprintf`.

**Review by iuhilnehc-ynos — APPROVED** [review]
LGTM

**Review by ahcorde — APPROVED** [review]

**Review by clalancette — CHANGES_REQUESTED** [review]
See my comment in https://github.com/ros2/rcl/pull/1035#pullrequestreview-1319926373 for why I don't think this is safe to do.

**Comment by fujitatomoya** [comment]
https://ci.ros2.org/job/ci_linux/18129/testReport/ is known flaky addressed by https://github.com/ros2/ros2cli/issues/809

**Comment by fujitatomoya** [comment]
@mergifyio backport humble

**Pull request merged**
